/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allavona.tfg.frontapp.business.webclient.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;

import com.allavona.tfg.frontapp.business.webclient.JSON;

/**
 * ClasificacionIncidenteDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-08T16:32:14.863738400+01:00[Europe/Madrid]")
public class ClasificacionIncidenteDTO {
  public static final String SERIALIZED_NAME_ID_CLASIFICACION_INCIDENTE = "idClasificacionIncidente";
  @SerializedName(SERIALIZED_NAME_ID_CLASIFICACION_INCIDENTE)
  private Integer idClasificacionIncidente;

  public static final String SERIALIZED_NAME_CODIGO = "codigo";
  @SerializedName(SERIALIZED_NAME_CODIGO)
  private String codigo;

  public static final String SERIALIZED_NAME_NOMBRE = "nombre";
  @SerializedName(SERIALIZED_NAME_NOMBRE)
  private String nombre;

  public ClasificacionIncidenteDTO() {
  }

  public ClasificacionIncidenteDTO idClasificacionIncidente(Integer idClasificacionIncidente) {
    
    this.idClasificacionIncidente = idClasificacionIncidente;
    return this;
  }

   /**
   * Get idClasificacionIncidente
   * @return idClasificacionIncidente
  **/
  @javax.annotation.Nullable

  public Integer getIdClasificacionIncidente() {
    return idClasificacionIncidente;
  }


  public void setIdClasificacionIncidente(Integer idClasificacionIncidente) {
    this.idClasificacionIncidente = idClasificacionIncidente;
  }


  public ClasificacionIncidenteDTO codigo(String codigo) {
    
    this.codigo = codigo;
    return this;
  }

   /**
   * Get codigo
   * @return codigo
  **/
  @javax.annotation.Nullable

  public String getCodigo() {
    return codigo;
  }


  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }


  public ClasificacionIncidenteDTO nombre(String nombre) {
    
    this.nombre = nombre;
    return this;
  }

   /**
   * Get nombre
   * @return nombre
  **/
  @javax.annotation.Nullable

  public String getNombre() {
    return nombre;
  }


  public void setNombre(String nombre) {
    this.nombre = nombre;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClasificacionIncidenteDTO clasificacionIncidenteDTO = (ClasificacionIncidenteDTO) o;
    return Objects.equals(this.idClasificacionIncidente, clasificacionIncidenteDTO.idClasificacionIncidente) &&
        Objects.equals(this.codigo, clasificacionIncidenteDTO.codigo) &&
        Objects.equals(this.nombre, clasificacionIncidenteDTO.nombre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idClasificacionIncidente, codigo, nombre);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClasificacionIncidenteDTO {\n");
    sb.append("    idClasificacionIncidente: ").append(toIndentedString(idClasificacionIncidente)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("idClasificacionIncidente");
    openapiFields.add("codigo");
    openapiFields.add("nombre");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ClasificacionIncidenteDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ClasificacionIncidenteDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClasificacionIncidenteDTO is not found in the empty JSON string", ClasificacionIncidenteDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ClasificacionIncidenteDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClasificacionIncidenteDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("codigo") != null && !jsonObj.get("codigo").isJsonNull()) && !jsonObj.get("codigo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codigo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codigo").toString()));
      }
      if ((jsonObj.get("nombre") != null && !jsonObj.get("nombre").isJsonNull()) && !jsonObj.get("nombre").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombre` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombre").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClasificacionIncidenteDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClasificacionIncidenteDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClasificacionIncidenteDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClasificacionIncidenteDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ClasificacionIncidenteDTO>() {
           @Override
           public void write(JsonWriter out, ClasificacionIncidenteDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClasificacionIncidenteDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ClasificacionIncidenteDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ClasificacionIncidenteDTO
  * @throws IOException if the JSON string is invalid with respect to ClasificacionIncidenteDTO
  */
  public static ClasificacionIncidenteDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClasificacionIncidenteDTO.class);
  }

 /**
  * Convert an instance of ClasificacionIncidenteDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

