/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allavona.tfg.frontapp.business.webclient.api;

import com.allavona.tfg.frontapp.business.webclient.ApiCallback;
import com.allavona.tfg.frontapp.business.webclient.ApiClient;
import com.allavona.tfg.frontapp.business.webclient.ApiException;
import com.allavona.tfg.frontapp.business.webclient.ApiResponse;
import com.allavona.tfg.frontapp.business.webclient.Configuration;
import com.allavona.tfg.frontapp.business.webclient.Pair;

import com.google.gson.reflect.TypeToken;


import com.allavona.tfg.frontapp.business.webclient.model.Login;
import com.allavona.tfg.frontapp.business.webclient.model.Usuario;
import org.springframework.stereotype.Service;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
@Service
public class UsersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UsersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UsersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for autenticar
     * @param login  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Credenciales incorrectas </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Login realizado correctamente </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call autenticarCall(Login login, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = login;

        // create path and map variables
        String localVarPath = "/v1/users/authenticate";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call autenticarValidateBeforeCall(Login login, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'login' is set
        if (login == null) {
            throw new ApiException("Missing the required parameter 'login' when calling autenticar(Async)");
        }

        return autenticarCall(login, _callback);

    }

    /**
     * Verificación de credenciales
     * Comprueba si la tupla usuario - contraseña introducidos son correctos
     * @param login  (required)
     * @return Usuario
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Credenciales incorrectas </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Login realizado correctamente </td><td>  -  </td></tr>
     </table>
     */
    public Usuario autenticar(Login login) throws ApiException {
        ApiResponse<Usuario> localVarResp = autenticarWithHttpInfo(login);
        return localVarResp.getData();
    }

    /**
     * Verificación de credenciales
     * Comprueba si la tupla usuario - contraseña introducidos son correctos
     * @param login  (required)
     * @return ApiResponse&lt;Usuario&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Credenciales incorrectas </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Login realizado correctamente </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Usuario> autenticarWithHttpInfo(Login login) throws ApiException {
        okhttp3.Call localVarCall = autenticarValidateBeforeCall(login, null);
        Type localVarReturnType = new TypeToken<Usuario>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Verificación de credenciales (asynchronously)
     * Comprueba si la tupla usuario - contraseña introducidos son correctos
     * @param login  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 401 </td><td> Credenciales incorrectas </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Login realizado correctamente </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call autenticarAsync(Login login, final ApiCallback<Usuario> _callback) throws ApiException {

        okhttp3.Call localVarCall = autenticarValidateBeforeCall(login, _callback);
        Type localVarReturnType = new TypeToken<Usuario>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
